version: '3.4'

x-environment:
  &default-environment
    AMAZEEIO: AMAZEEIO

services:
  php:
    build:
      context: ./api
      dockerfile: Dockerfile.php
    labels:
      lagoon.type: nginx-php
      lagoon.name: nginx
    depends_on:
      - mariadb
    env_file:
      - ./api/.env
    # Comment out these volumes in production
    volumes:
      - ./api:/srv/api:rw,cached
      # If you develop on Linux, uncomment the following line to use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw
    networks:
      - amazeeio-network
      - default

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.nginx
      args:
        PHP_IMAGE: api-platform_php
    labels:
      lagoon.type: nginx-php
      lagoon.name: nginx
      lagoon.deployment.servicetype: nginx
    depends_on:
      - php
    # Comment out this volume in production
    volumes:
      - ./api/public:/srv/api/public:ro
    environment:
      << : *default-environment
      LAGOON_LOCALDEV_URL: api-api-platform.docker.amazee.io
    networks:
      - amazeeio-network
      - default

  cache-proxy:
    build:
      context: ./api
      dockerfile: Dockerfile.varnish
    labels:
      lagoon.type: varnish
      lagoon.deployment.servicetype: varnish
    depends_on:
      - api
    volumes:
      - ./api/docker/varnish/conf:/usr/local/etc/varnish:ro
    tmpfs:
      - /usr/local/var/varnish:exec
    ports:
      - "8080"
    environment:
      << : *default-environment
      LAGOON_ROUTE: http://api-platform.docker.amazee.io
      AMAZEEIO_HTTP_PORT: 8080
    links:
      - api
    networks:
      - amazeeio-network
      - default

  mariadb:
    # In production, you may want to use a managed database service
    build:
      context: ./api
      dockerfile: Dockerfile.mariadb
    labels:
      lagoon.type: mariadb
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306"

  client:
    # Use a static website hosting service in production
    # See https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment
    build:
      context: ./client
      dockerfile: Dockerfile
    labels:
      lagoon.type: node
      lagoon.deployment.servicetype: node
    env_file:
      - ./client/.env
    volumes:
      - ./client:/usr/src/client:rw,cached
      - /usr/src/client/node_modules
    ports:
      - "3000"
    environment:
      << : *default-environment
      AMAZEEIO_HTTP_PORT: 3000
      AMAZEEIO_URL: client-api-platform.docker.amazee.io
    networks:
      - amazeeio-network
      - default
  admin:
    # Use a static website hosting service in production
    # See https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment
    build:
      context: ./admin
      dockerfile: Dockerfile
    labels:
      lagoon.type: node
      lagoon.deployment.servicetype: node
    env_file:
      - ./admin/.env
    volumes:
      - ./admin:/usr/src/admin:rw,cached
      - /usr/src/admin/node_modules
    ports:
      - "3000"
    environment:
      << : *default-environment
      AMAZEEIO_HTTP_PORT: 3000
      AMAZEEIO_URL: admin-api-platform.docker.amazee.io
    networks:
      - amazeeio-network
      - default

volumes:
  db-data: {}

networks:
  amazeeio-network:
    external: true
