ARG PHP_IMAGE
FROM ${PHP_IMAGE} as api_platform_php

FROM amazeeio/nginx AS api_platform_nginx

COPY docker/nginx/conf.d/default.conf /etc/nginx/conf.d/app.conf

WORKDIR /srv/api

FROM api_platform_php

COPY --from=api_platform_php /srv/api/public public/
